
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: eks-3nodes
    region: ap-southeast-1
nodeGroups:
    - name: spot-node-group-2vcpu-8gb
      minSize: 3
      maxSize: 5
      desiredCapacity: 3
      instancesDistribution:
        instanceTypes: ["m5.large", "m5d.large", "m4.large","m5a.large","m5ad.large","m5n.large","m5dn.large"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: "capacity-optimized"
      labels:
        lifecycle: Ec2Spot
      iam:
        withAddonPolicies:
          autoScaler: true
    - name: spot-node-group-4vcpu-16gb
      minSize: 3
      maxSize: 5
      desiredCapacity: 3
      instancesDistribution:
        instanceTypes: ["m5.xlarge", "m5d.xlarge", "m4.xlarge","m5a.xlarge","m5ad.xlarge","m5n.xlarge","m5dn.xlarge"] 
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotAllocationStrategy: "capacity-optimized"
      labels:
        lifecycle: Ec2Spot
      iam:
        withAddonPolicies:
          autoScaler: true